### ISSUE TITLE
Create a universal starter file

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/PEPtools#7]
Create a universal starter file that can be used for PEP. Could programmatically create it from simple or just save the file itself.

**Comment by k-doering-NOAA** [comment]
That's a great idea! I've wondered if the nmfs-stock-synthesis org should have a template set of files for users to start from, with start being the easiest to pinpoint defaults. 

I would vote for creating your own rather than creating it from simple, as I don't think the simple starter file is necessarily a conscious choice of defaults and therefore there isn't much need to track changes from the simple file.

Finally, if it makes sense to make the PEP starter file available to those outside of PEP, we could consider hosting it within the nmfs-stock-synthesis org.
